Repository meshery/meshery-linkerd, pull requests merged in 2021-12, with the labels that each got.

#251 [Draft] Bump the distroless image tag to fix cves
  Dockerfile
Labels: security

#261 [meshery-linkerd] Added kubeopenapi-jsonschema to meshery-linkerd image
  Dockerfile
Labels: kind/chore, area/ci

#262 [meshery-linkerd] updated go.mod version to 1.17 and updated dependencies
  go.mod
Labels: area/ci

#283 [UX] Minor update on spelling and logs
  main.go
Labels: kind/chore, service-mesh/linkerd
